### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by SemenMartynov** [stakenschneider/validationService#9]
Fix all issues and go to the 2nd task.

**Comment by SemenMartynov** [comment]
I don't see updated in documentation for the task 2.

**Comment by SemenMartynov** [comment]
```
$ curl --upload-file good.json http://localhost                                    
curl: (56) Recv failure: Connection reset by peer
$ curl --upload-file bad.json http://localhost                                     
curl: (56) Recv failure: Connection reset by peer

```

**Comment by SemenMartynov** [comment]
```
$ ./gradlew build docker
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

(you need to add gradle wrapper to your project)

**Comment by stakenschneider** [comment]
@SemenMartynov а какую ветку вы клонируете?

**Comment by SemenMartynov** [comment]
I'm taking zip package with the latest snapshot -- we disused on the 2nd seminar, that each commit in the main branch is the new product release...

**Comment by SemenMartynov** [comment]
OK, good work.
But what's wrong with your error message format?
Please, fix it -- https://github.com/SemenMartynov/SPbPU_TRPO_2017/blob/master/Task01.RUS.txt#L41

**Comment by stakenschneider** [comment]
@SemenMartynov что именно не так? Я видела формат, вроде все верно.

**Comment by SemenMartynov** [comment]
Hm... I can't show you, because something is broken here:
```
$ ./gradlew build dockerImage                                                                                     
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava
/media/basket/home/Documents/git/students/validationService/src/main/java/pack/Resource.java:39: error: cannot find symbol
            global++;
            ^
  symbol:   variable global
  location: class Resource
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 11s
1 actionable task: 1 executed
```

If I'm not mistake, you are showing file content instead of file name. Please check it.

**Comment by stakenschneider** [comment]
@SemenMartynov не, это просто результат корявого мерджа. Я поправила 281a84670639da3cc16146d0231bf9451eefc3f7

**Comment by SemenMartynov** [comment]
```
$ ./gradlew build dockerImage
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :dockerImage
Building image using context '/media/basket/home/Documents/git/students/validationService'.
Using tag 'validationService' for image.

[dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Error parsing reference: \"validationService\" is not a valid repository/tag: repository name must be lowercase"}

        at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerImage'.
> {"message":"Error parsing reference: \"validationService\" is not a valid repository/tag: repository name must be lowercase"}


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 23s
8 actionable tasks: 8 executed
```

**Comment by stakenschneider** [comment]
@SemenMartynov 5a81b40a2ce06c339186ad071707ad688fbfb511 fixed

**Comment by SemenMartynov** [comment]
OK
